/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as AuthedExpensesRouteRouteImport } from './routes/_authed/expenses/route'
import { Route as AuthedExpensesIndexRouteImport } from './routes/_authed/expenses/index'
import { Route as AuthedExpensesSettingsRouteImport } from './routes/_authed/expenses/settings'
import { Route as AuthedExpensesAccountsRouteImport } from './routes/_authed/expenses/accounts'
import { Route as AuthedExpensesTransactionsIndexRouteImport } from './routes/_authed/expenses/transactions/index'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedExpensesRouteRoute = AuthedExpensesRouteRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedExpensesIndexRoute = AuthedExpensesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedExpensesRouteRoute,
} as any)
const AuthedExpensesSettingsRoute = AuthedExpensesSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedExpensesRouteRoute,
} as any)
const AuthedExpensesAccountsRoute = AuthedExpensesAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthedExpensesRouteRoute,
} as any)
const AuthedExpensesTransactionsIndexRoute =
  AuthedExpensesTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => AuthedExpensesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/expenses': typeof AuthedExpensesRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/expenses/accounts': typeof AuthedExpensesAccountsRoute
  '/expenses/settings': typeof AuthedExpensesSettingsRoute
  '/expenses/': typeof AuthedExpensesIndexRoute
  '/expenses/transactions': typeof AuthedExpensesTransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/expenses/accounts': typeof AuthedExpensesAccountsRoute
  '/expenses/settings': typeof AuthedExpensesSettingsRoute
  '/expenses': typeof AuthedExpensesIndexRoute
  '/expenses/transactions': typeof AuthedExpensesTransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/expenses': typeof AuthedExpensesRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/_authed/expenses/accounts': typeof AuthedExpensesAccountsRoute
  '/_authed/expenses/settings': typeof AuthedExpensesSettingsRoute
  '/_authed/expenses/': typeof AuthedExpensesIndexRoute
  '/_authed/expenses/transactions/': typeof AuthedExpensesTransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/expenses'
    | '/api/$'
    | '/expenses/accounts'
    | '/expenses/settings'
    | '/expenses/'
    | '/expenses/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/$'
    | '/expenses/accounts'
    | '/expenses/settings'
    | '/expenses'
    | '/expenses/transactions'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/expenses'
    | '/api/$'
    | '/_authed/expenses/accounts'
    | '/_authed/expenses/settings'
    | '/_authed/expenses/'
    | '/_authed/expenses/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/expenses': {
      id: '/_authed/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthedExpensesRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/expenses/': {
      id: '/_authed/expenses/'
      path: '/'
      fullPath: '/expenses/'
      preLoaderRoute: typeof AuthedExpensesIndexRouteImport
      parentRoute: typeof AuthedExpensesRouteRoute
    }
    '/_authed/expenses/settings': {
      id: '/_authed/expenses/settings'
      path: '/settings'
      fullPath: '/expenses/settings'
      preLoaderRoute: typeof AuthedExpensesSettingsRouteImport
      parentRoute: typeof AuthedExpensesRouteRoute
    }
    '/_authed/expenses/accounts': {
      id: '/_authed/expenses/accounts'
      path: '/accounts'
      fullPath: '/expenses/accounts'
      preLoaderRoute: typeof AuthedExpensesAccountsRouteImport
      parentRoute: typeof AuthedExpensesRouteRoute
    }
    '/_authed/expenses/transactions/': {
      id: '/_authed/expenses/transactions/'
      path: '/transactions'
      fullPath: '/expenses/transactions'
      preLoaderRoute: typeof AuthedExpensesTransactionsIndexRouteImport
      parentRoute: typeof AuthedExpensesRouteRoute
    }
  }
}

interface AuthedExpensesRouteRouteChildren {
  AuthedExpensesAccountsRoute: typeof AuthedExpensesAccountsRoute
  AuthedExpensesSettingsRoute: typeof AuthedExpensesSettingsRoute
  AuthedExpensesIndexRoute: typeof AuthedExpensesIndexRoute
  AuthedExpensesTransactionsIndexRoute: typeof AuthedExpensesTransactionsIndexRoute
}

const AuthedExpensesRouteRouteChildren: AuthedExpensesRouteRouteChildren = {
  AuthedExpensesAccountsRoute: AuthedExpensesAccountsRoute,
  AuthedExpensesSettingsRoute: AuthedExpensesSettingsRoute,
  AuthedExpensesIndexRoute: AuthedExpensesIndexRoute,
  AuthedExpensesTransactionsIndexRoute: AuthedExpensesTransactionsIndexRoute,
}

const AuthedExpensesRouteRouteWithChildren =
  AuthedExpensesRouteRoute._addFileChildren(AuthedExpensesRouteRouteChildren)

interface AuthedRouteChildren {
  AuthedExpensesRouteRoute: typeof AuthedExpensesRouteRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedExpensesRouteRoute: AuthedExpensesRouteRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
