/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as AuthedNotesRouteRouteImport } from './routes/_authed/notes/route'
import { Route as AuthedExpensesRouteRouteImport } from './routes/_authed/expenses/route'
import { Route as AuthedNotesIndexRouteImport } from './routes/_authed/notes/index'
import { Route as AuthedExpensesIndexRouteImport } from './routes/_authed/expenses/index'
import { Route as AuthedNotesTodosRouteImport } from './routes/_authed/notes/todos'
import { Route as AuthedNotesListRouteImport } from './routes/_authed/notes/list'
import { Route as AuthedNotesJournalRouteImport } from './routes/_authed/notes/journal'
import { Route as AuthedNotesHabitsRouteImport } from './routes/_authed/notes/habits'
import { Route as AuthedExpensesSettingsRouteImport } from './routes/_authed/expenses/settings'
import { Route as AuthedExpensesAccountsRouteImport } from './routes/_authed/expenses/accounts'
import { Route as AuthedExpensesTransactionsIndexRouteImport } from './routes/_authed/expenses/transactions/index'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedNotesRouteRoute = AuthedNotesRouteRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedExpensesRouteRoute = AuthedExpensesRouteRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNotesIndexRoute = AuthedNotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedNotesRouteRoute,
} as any)
const AuthedExpensesIndexRoute = AuthedExpensesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedExpensesRouteRoute,
} as any)
const AuthedNotesTodosRoute = AuthedNotesTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => AuthedNotesRouteRoute,
} as any)
const AuthedNotesListRoute = AuthedNotesListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => AuthedNotesRouteRoute,
} as any)
const AuthedNotesJournalRoute = AuthedNotesJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AuthedNotesRouteRoute,
} as any)
const AuthedNotesHabitsRoute = AuthedNotesHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => AuthedNotesRouteRoute,
} as any)
const AuthedExpensesSettingsRoute = AuthedExpensesSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedExpensesRouteRoute,
} as any)
const AuthedExpensesAccountsRoute = AuthedExpensesAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthedExpensesRouteRoute,
} as any)
const AuthedExpensesTransactionsIndexRoute =
  AuthedExpensesTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => AuthedExpensesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/expenses': typeof AuthedExpensesRouteRouteWithChildren
  '/notes': typeof AuthedNotesRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/expenses/accounts': typeof AuthedExpensesAccountsRoute
  '/expenses/settings': typeof AuthedExpensesSettingsRoute
  '/notes/habits': typeof AuthedNotesHabitsRoute
  '/notes/journal': typeof AuthedNotesJournalRoute
  '/notes/list': typeof AuthedNotesListRoute
  '/notes/todos': typeof AuthedNotesTodosRoute
  '/expenses/': typeof AuthedExpensesIndexRoute
  '/notes/': typeof AuthedNotesIndexRoute
  '/expenses/transactions': typeof AuthedExpensesTransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/expenses/accounts': typeof AuthedExpensesAccountsRoute
  '/expenses/settings': typeof AuthedExpensesSettingsRoute
  '/notes/habits': typeof AuthedNotesHabitsRoute
  '/notes/journal': typeof AuthedNotesJournalRoute
  '/notes/list': typeof AuthedNotesListRoute
  '/notes/todos': typeof AuthedNotesTodosRoute
  '/expenses': typeof AuthedExpensesIndexRoute
  '/notes': typeof AuthedNotesIndexRoute
  '/expenses/transactions': typeof AuthedExpensesTransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/expenses': typeof AuthedExpensesRouteRouteWithChildren
  '/_authed/notes': typeof AuthedNotesRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/_authed/expenses/accounts': typeof AuthedExpensesAccountsRoute
  '/_authed/expenses/settings': typeof AuthedExpensesSettingsRoute
  '/_authed/notes/habits': typeof AuthedNotesHabitsRoute
  '/_authed/notes/journal': typeof AuthedNotesJournalRoute
  '/_authed/notes/list': typeof AuthedNotesListRoute
  '/_authed/notes/todos': typeof AuthedNotesTodosRoute
  '/_authed/expenses/': typeof AuthedExpensesIndexRoute
  '/_authed/notes/': typeof AuthedNotesIndexRoute
  '/_authed/expenses/transactions/': typeof AuthedExpensesTransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/expenses'
    | '/notes'
    | '/api/$'
    | '/expenses/accounts'
    | '/expenses/settings'
    | '/notes/habits'
    | '/notes/journal'
    | '/notes/list'
    | '/notes/todos'
    | '/expenses/'
    | '/notes/'
    | '/expenses/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/$'
    | '/expenses/accounts'
    | '/expenses/settings'
    | '/notes/habits'
    | '/notes/journal'
    | '/notes/list'
    | '/notes/todos'
    | '/expenses'
    | '/notes'
    | '/expenses/transactions'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/expenses'
    | '/_authed/notes'
    | '/api/$'
    | '/_authed/expenses/accounts'
    | '/_authed/expenses/settings'
    | '/_authed/notes/habits'
    | '/_authed/notes/journal'
    | '/_authed/notes/list'
    | '/_authed/notes/todos'
    | '/_authed/expenses/'
    | '/_authed/notes/'
    | '/_authed/expenses/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/notes': {
      id: '/_authed/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthedNotesRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/expenses': {
      id: '/_authed/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthedExpensesRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/notes/': {
      id: '/_authed/notes/'
      path: '/'
      fullPath: '/notes/'
      preLoaderRoute: typeof AuthedNotesIndexRouteImport
      parentRoute: typeof AuthedNotesRouteRoute
    }
    '/_authed/expenses/': {
      id: '/_authed/expenses/'
      path: '/'
      fullPath: '/expenses/'
      preLoaderRoute: typeof AuthedExpensesIndexRouteImport
      parentRoute: typeof AuthedExpensesRouteRoute
    }
    '/_authed/notes/todos': {
      id: '/_authed/notes/todos'
      path: '/todos'
      fullPath: '/notes/todos'
      preLoaderRoute: typeof AuthedNotesTodosRouteImport
      parentRoute: typeof AuthedNotesRouteRoute
    }
    '/_authed/notes/list': {
      id: '/_authed/notes/list'
      path: '/list'
      fullPath: '/notes/list'
      preLoaderRoute: typeof AuthedNotesListRouteImport
      parentRoute: typeof AuthedNotesRouteRoute
    }
    '/_authed/notes/journal': {
      id: '/_authed/notes/journal'
      path: '/journal'
      fullPath: '/notes/journal'
      preLoaderRoute: typeof AuthedNotesJournalRouteImport
      parentRoute: typeof AuthedNotesRouteRoute
    }
    '/_authed/notes/habits': {
      id: '/_authed/notes/habits'
      path: '/habits'
      fullPath: '/notes/habits'
      preLoaderRoute: typeof AuthedNotesHabitsRouteImport
      parentRoute: typeof AuthedNotesRouteRoute
    }
    '/_authed/expenses/settings': {
      id: '/_authed/expenses/settings'
      path: '/settings'
      fullPath: '/expenses/settings'
      preLoaderRoute: typeof AuthedExpensesSettingsRouteImport
      parentRoute: typeof AuthedExpensesRouteRoute
    }
    '/_authed/expenses/accounts': {
      id: '/_authed/expenses/accounts'
      path: '/accounts'
      fullPath: '/expenses/accounts'
      preLoaderRoute: typeof AuthedExpensesAccountsRouteImport
      parentRoute: typeof AuthedExpensesRouteRoute
    }
    '/_authed/expenses/transactions/': {
      id: '/_authed/expenses/transactions/'
      path: '/transactions'
      fullPath: '/expenses/transactions'
      preLoaderRoute: typeof AuthedExpensesTransactionsIndexRouteImport
      parentRoute: typeof AuthedExpensesRouteRoute
    }
  }
}

interface AuthedExpensesRouteRouteChildren {
  AuthedExpensesAccountsRoute: typeof AuthedExpensesAccountsRoute
  AuthedExpensesSettingsRoute: typeof AuthedExpensesSettingsRoute
  AuthedExpensesIndexRoute: typeof AuthedExpensesIndexRoute
  AuthedExpensesTransactionsIndexRoute: typeof AuthedExpensesTransactionsIndexRoute
}

const AuthedExpensesRouteRouteChildren: AuthedExpensesRouteRouteChildren = {
  AuthedExpensesAccountsRoute: AuthedExpensesAccountsRoute,
  AuthedExpensesSettingsRoute: AuthedExpensesSettingsRoute,
  AuthedExpensesIndexRoute: AuthedExpensesIndexRoute,
  AuthedExpensesTransactionsIndexRoute: AuthedExpensesTransactionsIndexRoute,
}

const AuthedExpensesRouteRouteWithChildren =
  AuthedExpensesRouteRoute._addFileChildren(AuthedExpensesRouteRouteChildren)

interface AuthedNotesRouteRouteChildren {
  AuthedNotesHabitsRoute: typeof AuthedNotesHabitsRoute
  AuthedNotesJournalRoute: typeof AuthedNotesJournalRoute
  AuthedNotesListRoute: typeof AuthedNotesListRoute
  AuthedNotesTodosRoute: typeof AuthedNotesTodosRoute
  AuthedNotesIndexRoute: typeof AuthedNotesIndexRoute
}

const AuthedNotesRouteRouteChildren: AuthedNotesRouteRouteChildren = {
  AuthedNotesHabitsRoute: AuthedNotesHabitsRoute,
  AuthedNotesJournalRoute: AuthedNotesJournalRoute,
  AuthedNotesListRoute: AuthedNotesListRoute,
  AuthedNotesTodosRoute: AuthedNotesTodosRoute,
  AuthedNotesIndexRoute: AuthedNotesIndexRoute,
}

const AuthedNotesRouteRouteWithChildren =
  AuthedNotesRouteRoute._addFileChildren(AuthedNotesRouteRouteChildren)

interface AuthedRouteChildren {
  AuthedExpensesRouteRoute: typeof AuthedExpensesRouteRouteWithChildren
  AuthedNotesRouteRoute: typeof AuthedNotesRouteRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedExpensesRouteRoute: AuthedExpensesRouteRouteWithChildren,
  AuthedNotesRouteRoute: AuthedNotesRouteRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
